### ISSUE TITLE
Load crash

### ISSUE THREAD

**Issue by al-wei** [Invadermonky/JustEnoughMagiculture#12] opened 2024-06-16 16:57 UTC
https://github.com/Invadermonky/JustEnoughMagiculture/issues

**Comment by Invadermonky** [comment] 2024-06-16 18:55
The link you provided redirects to JEM's issue page. Please submit a crashlog.

**Comment by al-wei** [comment] 2024-06-17 14:01
> The link you provided redirects to JEM's issue page. Please submit a crashlog.

Sorry for copying the wrong link.
https://gist.github.com/al-wei/32bb386cc4a85f78ecc2a0f63ab5cafa

**Comment by al-wei** [comment] 2024-06-17 14:18
> The link you provided redirects to JEM's issue page. Please submit a crashlog.

Oh, there's another mod for you to work on.
https://legacy.curseforge.com/minecraft/mc-mods/villager-market-nbt-fix/issues

**Comment by al-wei** [comment] 2024-09-01 09:12
Conflict with Elemental Items.

https://www.curseforge.com/minecraft/mc-mods/elemental-items/screenshots

**Comment by Invadermonky** [comment] 2024-10-06 05:55
I have been unable to reproduce the crash in any of my environments. As of version  [1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394) I forced JEM to load after Elemental Items which may fix the issue.

**Comment by al-wei** [comment] 2024-10-06 13:48
> I have been unable to reproduce the crash in any of my environments. As of version [1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394) I forced JEM to load after Elemental Items which may fix the issue.

Version 1.2 successfully entered the game.
1.1.5:Version 1.1.5, still crashes when loaded alone.
https://mclo.gs/wceKj1F

**Comment by Invadermonky** [comment] 2024-10-06 16:48
If the crash is no longer occurring then I am going to close this comment as fixed/complete as of version [1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394).

**Closed by Invadermonky** 2024-10-06 16:48 UTC
