### ISSUE TITLE
Crash on startup with LootTableTweaker + Living Enchantments installed, even with all configs set to 'false'

### ISSUE THREAD

**Issue by jacobmaj** [Invadermonky/JustEnoughMagiculture#2] opened 2024-01-17 09:43 UTC
As per the title, I was unable to load into the game unless one of these mods were disabled.
Crashlog:
https://pastebin.com/9VdwUkSt

**Comment by Invadermonky** [comment] 2024-01-18 07:07
I am unable to reproduce this crash even with the same load order. What scripts are you using that modify loot tables?

**Comment by jacobmaj** [comment] 2024-01-18 19:23
I managed to get the same crash with just a few mods, and two script lines:
https://pastebin.com/5mksXg3A


My LootTableTweaker script:

`
import mods.ltt.LootTable;

LootTable.removeGlobalItem("minecraft:apple");
`

**Comment by Invadermonky** [comment] 2024-01-18 22:28
I was able to run the game without issue using the same load order with the same script (added rotten flesh to show that it is working).
`import mods.ltt.LootTable;

LootTable.removeGlobalItem("minecraft:apple");
LootTable.removeGlobalItem("minecraft:rotten_flesh");`
![image](https://github.com/Invadermonky/JustEnoughMagiculture/assets/101663980/50608a6d-1a61-4e94-902d-d6f06a83c66e)

Though it looks like you are running an alpha release of JER (version 1.12.2-0.9.3.203). JEM was built on the latest stable release of JER (version 1.12.2-0.9.2.60).

From the changelog, it looks like that the JER alpha build only adds beetroot, nether wart, and polar bears to the JER categories. JEM handles these already so there should be no change if you roll back JER.

**Comment by jacobmaj** [comment] 2024-01-19 01:43
It appears Living Enchantment + LootTableTweaker is needed to induce the crash. I have also tried running with JER 0.9.2.60 to no success:

https://pastebin.com/7ujnYu9v

**Comment by Invadermonky** [comment] 2024-01-19 01:54
Missed the Living Enchantment on the load order, my bad. I am able to reproduce the crash and will start tracking down the cause.

**Comment by Invadermonky** [comment] 2024-01-19 02:42
## Update:
Have a fix for it. The entire issue was caused by all sorts of screwy going on in the background as three different mods were fighting over control over fake loot tables (used by JER's JEI displays).

Living Enchantment was injecting it's own loot into the loot tables as LootTableTweaker was modifying said tables and JEM was trying to access the loot manager (which requires reloading the loot tables) as that entire mess was going on.

## Steps to Reproduce:
- Mods Installed:
  - JEM
  - Living Enchantment
  - LootTableTweaker
- Modify global loot tables with LootTableTweaker
- ???
- Profit.

### Fixed with version 1.12.2-1.1.2.

**Closed by Invadermonky** 2024-01-19 02:42 UTC
