### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by xJon** [Invadermonky/JustEnoughMagiculture#11] opened 2024-06-02 12:41 UTC
https://mclo.gs/6xp5mMz

Seems to mention LootTweaker, and also reminds me of this [this](https://github.com/michelegargiulo/Witchery-Companion/issues/9) Witchery loot issue. Any idea what's causing it?

**Comment by Invadermonky** [comment] 2024-06-02 20:51
Can you check to see if this version fixes the issue?

[justenoughmagiculture-1.12.2-1.2.0.jar.zip](https://github.com/user-attachments/files/15526857/justenoughmagiculture-1.12.2-1.2.0.jar.zip)

**Comment by xJon** [comment] 2024-06-02 22:32
@Invadermonky An error still appears in the log albeit it is slightly different: https://mclo.gs/EXM90Yi

**Comment by xJon** [comment] 2024-06-02 22:48
I tested it for a bit and can reproduce it with this minimal set of mods:
![image](https://github.com/Invadermonky/JustEnoughMagiculture/assets/8945347/74b463dd-62c3-4b23-8b81-69cc8e881be6)

**Comment by Invadermonky** [comment] 2024-06-02 23:59
I tracked down the issue and it is actually caused by LootTweaker.

### The short version
LootTweaker uses mixins to patch vanilla MC's `LootTable` initialization. For the Loot Bag JEI category, JEM has to create a new loot table from Thaumcraft's `WeightedRandomLoot` API. The mixin, combined with JEM's client-side only implementation, is causing a null pointer exception that prevents the loot bag JEI category from loading.

### The Verdict
Actually fixing this error on my part would involve completely rewriting the way the the `LootBagEntry` is coded. While I do want to improve how the category is handled, the actual fix is a long way out (no ETA). You can either report this to the LootTweaker mod dev or ignore the issue.

**Comment by Daomephsta** [comment] 2024-06-03 04:43
This error occurs when LootTweaker attempts to report a duplicate loot entry name, but cannot get the ID of the loot table.

It shouldn't crash, that's something I need to fix. 
It looks like JEM is creating loot tables to make Thaumcraft's WeightedRandomLoot visible in Just Enough Resources?
If that's correct, I can make LootTweaker's autofixer ignore such loot tables, because they're an implementation detail. The errors it fixes only matter when the loot table is something a user would want to modify.

**Comment by Invadermonky** [comment] 2024-06-04 05:31
> It looks like JEM is creating loot tables to make Thaumcraft's WeightedRandomLoot visible in Just Enough Resources?

That is exactly what JEM does. I was (and still am) trying to figure out the best way to handle new JEI integrations so I ended up using JER's existing loot table handler to create the Loot Bag category. (Translation: *I hate GUIs*)

The tables created are just kinda crappy attempts to smash two different API's together and create something working. If you are aware of a better way to handle these sorts of tables, I would love to know.

**Comment by Daomephsta** [comment] 2024-06-13 10:08
LootTweaker should no longer crash here as of 0.4.1

**Comment by Invadermonky** [comment] 2024-06-14 18:43
Tested and appears to be working. Closing this issue as fixed as of [LootTweaker version 0.4.1](https://www.curseforge.com/minecraft/mc-mods/loottweaker/files/5420240).

**Closed by Invadermonky** 2024-06-14 18:43 UTC
